spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/mafia
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ
  token-validity-in-seconds: 86400
